// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "user_ir_cust_mappings",
    columns: [
      { name: "user_id", type: "string", unique: true },
      { name: "ir_cust_id", type: "string" },
      { name: "verify_code", type: "int" },
      { name: "is_verified", type: "bool", defaultValue: "false" },
      { name: "msg_sent", type: "bool", notNull: true, defaultValue: "false" },
      { name: "try_count", type: "int", notNull: true, defaultValue: "0" },
    ],
  },
  {
    name: "leagues",
    columns: [
      { name: "league_id", type: "int", unique: true },
      { name: "name", type: "string" },
      { name: "short_name", type: "string" },
    ],
  },
  {
    name: "users_leagues_interest",
    columns: [
      { name: "league_id", type: "int" },
      { name: "user_id", type: "string" },
    ],
  },
  {
    name: "journalists_leagues",
    columns: [
      { name: "journalist_id", type: "string" },
      { name: "league_id", type: "int" },
    ],
  },
  {
    name: "journalists",
    columns: [
      { name: "style_name", type: "string" },
      { name: "display_name", type: "string" },
      { name: "fine_tuning_prompt", type: "text" },
    ],
  },
  {
    name: "seasons",
    columns: [
      { name: "season_id", type: "int" },
      { name: "league_id", type: "int" },
      { name: "display_name", type: "string" },
      { name: "car_id", type: "int" },
      { name: "is_active", type: "bool" },
    ],
  },
  {
    name: "sched_subsessions",
    columns: [
      { name: "season_id", type: "int" },
      { name: "time", type: "datetime" },
      { name: "track_id", type: "int" },
      { name: "display_name", type: "string" },
    ],
  },
  {
    name: "tracks",
    columns: [
      { name: "display_name", type: "string" },
      { name: "short_name", type: "string" },
      { name: "track_id", type: "int" },
    ],
  },
  {
    name: "teams",
    columns: [
      { name: "display_name", type: "string" },
      { name: "season_id", type: "int" },
    ],
  },
  {
    name: "teams_users",
    columns: [
      { name: "ir_cust_id", type: "int" },
      { name: "team_id", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type UserIrCustMappings = InferredTypes["user_ir_cust_mappings"];
export type UserIrCustMappingsRecord = UserIrCustMappings & XataRecord;

export type Leagues = InferredTypes["leagues"];
export type LeaguesRecord = Leagues & XataRecord;

export type UsersLeaguesInterest = InferredTypes["users_leagues_interest"];
export type UsersLeaguesInterestRecord = UsersLeaguesInterest & XataRecord;

export type JournalistsLeagues = InferredTypes["journalists_leagues"];
export type JournalistsLeaguesRecord = JournalistsLeagues & XataRecord;

export type Journalists = InferredTypes["journalists"];
export type JournalistsRecord = Journalists & XataRecord;

export type Seasons = InferredTypes["seasons"];
export type SeasonsRecord = Seasons & XataRecord;

export type SchedSubsessions = InferredTypes["sched_subsessions"];
export type SchedSubsessionsRecord = SchedSubsessions & XataRecord;

export type Tracks = InferredTypes["tracks"];
export type TracksRecord = Tracks & XataRecord;

export type Teams = InferredTypes["teams"];
export type TeamsRecord = Teams & XataRecord;

export type TeamsUsers = InferredTypes["teams_users"];
export type TeamsUsersRecord = TeamsUsers & XataRecord;

export type DatabaseSchema = {
  user_ir_cust_mappings: UserIrCustMappingsRecord;
  leagues: LeaguesRecord;
  users_leagues_interest: UsersLeaguesInterestRecord;
  journalists_leagues: JournalistsLeaguesRecord;
  journalists: JournalistsRecord;
  seasons: SeasonsRecord;
  sched_subsessions: SchedSubsessionsRecord;
  tracks: TracksRecord;
  teams: TeamsRecord;
  teams_users: TeamsUsersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://arturo-mayorga-s-workspace-3e5jp6.us-east-1.xata.sh/db/bfr-leapdb",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
