/**
 * Bot-aware OG (Open Graph) preview middleware.
 *
 * The app is a SPA (`ssr: false`), so link unfurlers like Discord, Slack,
 * Twitter, etc. — which fetch HTML but do not execute JavaScript — see
 * only the empty shell with a generic title/icon for every URL. This
 * middleware short-circuits those bots: when the User-Agent matches a
 * known unfurler and the request is for the SPA root (`/`), we return a
 * minimal HTML document populated with `og:*` / `twitter:*` / oEmbed
 * metadata derived from the URL's query string.
 *
 * Real users' browsers don't match the regex, so they continue through
 * to the SPA shell unchanged. The image referenced by `og:image` is
 * generated by `/api/og?...`, which receives the same query string and
 * renders a card visually matching the page the user will see when they
 * click through.
 */

import { isBotUserAgent, escapeHtml, getRequestOrigin } from '../utils/og-bot';
import { buildResultsOgPayload } from '../utils/og-render-results';
import type { OgPayload } from '../utils/og-render-results';
import type { H3Event } from 'h3';

const DEFAULT_PAYLOAD: Omit<OgPayload, 'ogUrl' | 'imageUrl'> = {
    title: 'LEAP — Live Event Analysis and Performance',
    description:
        'Sim racing analytics for iRacing leagues — results, standings, charts, and event analysis.',
};

function buildDefaultPayload(event: H3Event): OgPayload {
    const origin = getRequestOrigin(event);
    return {
        ...DEFAULT_PAYLOAD,
        ogUrl: `${origin}${event.node.req.url || '/'}`,
        // Generic card. The image endpoint will fall back to a LEAP
        // brand card when no `m=...` mode is present.
        imageUrl: `${origin}/api/og`,
    };
}

async function payloadForMode(
    event: H3Event,
    mode: string,
    query: Record<string, string>
): Promise<OgPayload> {
    switch (mode) {
        case 'results':
            return buildResultsOgPayload(event, query);
        // Other modes (standings, paceChart, track, ...) will be added by
        // following the same shape as buildResultsOgPayload. Until then
        // bots get the brand-level card, which is still better than the
        // SPA-shell preview they see today.
        default:
            return buildDefaultPayload(event);
    }
}

function renderOgHtml(payload: OgPayload, oembedUrl: string): string {
    const t = escapeHtml(payload.title);
    const d = escapeHtml(payload.description);
    const u = escapeHtml(payload.ogUrl);
    const img = escapeHtml(payload.imageUrl);
    const oembed = escapeHtml(oembedUrl);
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>${t}</title>
<meta name="description" content="${d}"/>

<meta property="og:type" content="website"/>
<meta property="og:site_name" content="LEAP"/>
<meta property="og:title" content="${t}"/>
<meta property="og:description" content="${d}"/>
<meta property="og:url" content="${u}"/>
<meta property="og:image" content="${img}"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>

<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="${t}"/>
<meta name="twitter:description" content="${d}"/>
<meta name="twitter:image" content="${img}"/>

<link rel="alternate" type="application/json+oembed"
      href="${oembed}" title="${t}"/>
<link rel="canonical" href="${u}"/>
</head>
<body>
<h1>${t}</h1>
<p>${d}</p>
<p><a href="${u}">Open in LEAP</a></p>
</body>
</html>`;
}

function queryToRecord(event: H3Event): Record<string, string> {
    const raw = getQuery(event);
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(raw || {})) {
        if (v == null) continue;
        out[k] = Array.isArray(v) ? String(v[0]) : String(v);
    }
    return out;
}

export default defineEventHandler(async (event) => {
    // Method check first — only GET/HEAD trigger an unfurl. Anything else
    // (Clerk auth POSTs, prefetch loads) falls through untouched.
    const method = event.node.req.method || 'GET';
    if (method !== 'GET' && method !== 'HEAD') return;

    // Only the SPA root path is a shareable URL. API routes and assets
    // must never be intercepted — they need to behave normally even
    // when a bot probes them.
    const url = event.node.req.url || '';
    const pathname = url.split('?')[0];
    if (pathname !== '/' && pathname !== '') return;

    const ua = event.node.req.headers['user-agent'];
    if (!isBotUserAgent(Array.isArray(ua) ? ua[0] : ua)) return;

    const query = queryToRecord(event);
    const mode = query.m || '';

    try {
        const payload = await payloadForMode(event, mode, query);
        const oembedUrl = `${getRequestOrigin(
            event
        )}/api/oembed?${new URLSearchParams(query).toString()}`;
        const html = renderOgHtml(payload, oembedUrl);

        setResponseHeader(event, 'content-type', 'text/html; charset=utf-8');
        // Bot unfurlers cache for ~30 minutes anyway; let CDNs hold the
        // stub for an hour and serve while-revalidating beyond that.
        setResponseHeader(
            event,
            'cache-control',
            'public, max-age=300, s-maxage=3600, stale-while-revalidate=86400'
        );
        return html;
    } catch (e) {
        // If anything in the OG path fails, fall through to the SPA
        // shell rather than returning a broken preview. Bots will see
        // the generic shell — same as today — and we'll get a server
        // log to investigate.
        console.error('[og-bot] failed to render OG stub', e);
        return;
    }
});
